// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GameState is the predicate function for gamestate builders.
type GameState func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
